---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-argocd-aoa
  namespace: argocd
spec:
  destination:
    namespace: argocd
    #name: in-cluster
  project: default
  source:
    repoURL: https://github.com/Haibread/infrastructure.git
    path: kubernetes/apps/production/
    targetRevision: "HEAD"
    directory:
      recurse: true
  syncPolicy:
    automated: {}
