apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production-argocd
  namespace: argocd
spec:
  description: "Production Cluster"
  sourceRepos:
    - "https://github.com/Haibread/infrastructure.git"
  destinations:
    - namespace: "argocd"
      server: https://kubernetes.default.svc
    - namespace: "monitoring"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - kind: "*"
      group: "*"
  namespaceResourceWhitelist:
    - kind: "*"
      group: "*"