---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana-mimir
  namespace: monitoring
spec:
  path: "./kubernetes/apps/base/monitoring/grafana-mimir/app/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 10m
  retryInterval: 1m
  timeout: 3m