apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-mimir
  namespace: monitoring
spec:
  releasename: grafana-mimir
  chart:
    spec:
      chart: mimir-distributed
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      valuesFiles:
        - values.yaml
      interval: 5m