---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../base/monitoring/grafana/app
patches:
  - path: values.yaml
    target:
      kind: HelmRelease