apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    scaleway:
      region: {{ .Values.secretStore.region | quote}}
      projectId: {{ .Values.secretStore.projectId}}
      accessKey:
        value: {{ .Values.secretStore.accessKey.value}}
      secretKey:
        secretRef:
          name: {{ .Values.secretStore.secretKey.secretRef.name}}
          key: {{ .Values.secretStore.secretKey.secretRef.key}}
          namespace: {{ .Values.secretStore.secretKey.secretRef.namespace}}